name: Action

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions:checkout@v4.1.1
      - name: Run my own container action 
        uses: ./.github/actions
        with:
          who-to-greet: '@effectivelywild'
